[project]
name = "nonebot-plugin-htmlkit"
version = "0.1.0"
description = "Lightweight HTML rendering plugin for NoneBot"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["xmake_python"]
build-backend = "xmake_python"