name: Build Wheels
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - before-build: ""
            container: null
            repair: ""
            activate: "source .venv/bin/activate"
            replace-name: ""
            pick-wheel: "$(ls ../plugin-htmlkit/wheelhouse/*.whl | head -n1)"
          - os: ubuntu-latest
            container:
              image: quay.io/pypa/manylinux_2_34_x86_64
            repair: "auditwheel repair dist/*.whl -w wheelhouse"
            replace-name: "sed -i -e 's/name = \"nonebot-plugin-htmlkit\"/name = \"test-env\"/' pyproject.toml"
          - os: windows-latest
            repair: "delvewheel repair dist/*.whl -w wheelhouse"
            activate: ".venv/Scripts/activate"
            before-build: "cp .venv/Scripts/python.exe .venv/Scripts/python3.exe" # workaround xmake check for python3 executable
            replace-name: (Get-Content pyproject.toml) -replace 'name = "nonebot-plugin-htmlkit"', 'name = "test-env"' | Set-Content pyproject.toml
            pick-wheel: "(Get-ChildItem ..\\plugin-htmlkit\\wheelhouse\\*.whl | Select-Object -First 1).FullName"
          - os: macos-latest
            repair: "delocate-wheel -w wheelhouse dist/*.whl"
            replace-name: "sed -i '' -e 's/name = \"nonebot-plugin-htmlkit\"/name = \"test-env\"/' pyproject.toml"
    env:
      XMAKE_ROOT: 'y'
      MACOSX_DEPLOYMENT_TARGET: '11.0'

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install UV
        uses: astral-sh/setup-uv@v6
      - name: Install XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          package-cache-key: packages-${{ matrix.os }}-${{ hashFiles('xmake.lua', 'litehtml/**') }}
          project-path: .
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: xmake-${{ matrix.os }}-${{ hashFiles('xmake.lua') }}
      - name: Pin Python Version
        run: uv python pin 3.10.11
      - name: Build wheels
        run: |
          git config --global --add safe.directory '*'
          uv venv
          ${{ matrix.before-build }}
          ${{ matrix.activate }}
          uv sync --only-group build --no-install-workspace
          uv build
          ${{ matrix.repair }}
        env:
          XMAKE_ROOT: 'y'
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
      - name: Run Test
        run: |
          cd ../
          mkdir test-env
          cd test-env
          uv python pin 3.13
          uv venv
          ${{ matrix.activate }}
          cp -r ../plugin-htmlkit/tests/ ./tests
          cp ../plugin-htmlkit/pyproject.toml ./pyproject.toml
          ${{ matrix.replace-name }}
          uv sync --group test --no-install-workspace
          uv add ${{ matrix.pick-wheel }} --no-install-workspace
          uv run pytest